const CONFIG = {
    titleWeb: "Gửi "cà rốt" ",
    introTitle: 'Crush à',
    introDesc: `Soái ca là của ngôn tình. Còn anh thì chỉ của mình em thôi.`,
    btnIntro: '^^HiHi^^',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 🥰',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại say mình <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Tối nay 7h, câu đi chơi với mình nha😘',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://hkh5/crush.io
